/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#2b4a184e242f9ec520df46c2ca12e29ab7d40b08
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _StringDecs, _PunctuatorDecs, _KeywordDecs, _AnyDecs;
import { re, spam as m } from '@bablr/boot';
import { extendLanguage, o, eat, match } from '@bablr/helpers/grammar';
import { CoveredBy, Node, InjectFrom } from '@bablr/helpers/decorators';
import * as Space from '@bablr/language-en-blank-space';
import * as CSTML from '@bablr/language-en-cstml';
import * as Spamex from '@bablr/language-en-spamex';
import * as Regex from '@bablr/language-en-regex-vm-pattern';
import * as JSON from '@bablr/language-en-cstml-json';
import * as productions from '@bablr/helpers/productions';
import { buildString } from '@bablr/helpers/builders';
export const canonicalURL = 'https://bablr.org/languages/core/en/bablr-vm-instruction';
export function* eatMatchTrivia() {
  if (yield match(re`/[ \t\n]/`)) {
    return yield eat(m`#: <*Space:Space />`);
  }
  return null;
}
const IJSON = extendLanguage(JSON, {
  canonicalURL: 'https://github.com/bablr-lang/language-en-bablr-vm-instruction-json',
  dependencies: {
    Instruction: canonicalURL
  },
  grammar: class IJSON extends JSON.grammar {
    *Expression(props) {
      if (yield match(re`/(m|re|t)['"\u0060]/`)) {
        yield eat(m`<Instruction:Expression />`);
      } else {
        yield* super.Expression(props);
      }
    }
  }
});
export const dependencies = {
  Space,
  CSTML,
  Spamex,
  Regex,
  JSON,
  IJSON
};
export const grammar = class BABLRVMInstructionGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Call"], [Node, 2, "SpamexString"], [Node, 2, "CSTMLString"], [Node, 2, "RegexString"], [_StringDecs, 2, "String"], [Node, 2, "Identifier"], [_PunctuatorDecs, 2, "Punctuator"], [_KeywordDecs, 2, "Keyword"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_StringDecs = [CoveredBy('IJSONExpression'), CoveredBy('Expression'), Node], _PunctuatorDecs = [Node, InjectFrom(productions)], _KeywordDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), "Call")]() {
    yield eat(m`callee$: <*Identifier />`);
    yield* eatMatchTrivia();
    yield eat(m`openToken: <*Punctuator '(' { balanced: ')' } />`);
    let sp = yield* eatMatchTrivia();
    let first = true;
    while ((first || sp) && (yield match(re`/./`))) {
      yield eat(m`values[]$: <Expression />`);
      sp = yield* eatMatchTrivia();
      first = false;
    }
    yield eat(m`closeToken: <*Punctuator ')' { balancer: true } />`);
  }
  *Expression() {
    yield eat(m`<Any />`, [m`<IJSON:Array '[' />`, m`<IJSON:Object '{' />`, m`<*JSON:Boolean /true|false/ />`, m`<*JSON:Null 'null' />`, m`<JSON:Number /[\d]|[+-]?Infinity/ />`, m`<SpamexString /m["'\u0060]/ />`, m`<CSTMLString /t["'\u0060]/ />`, m`<RegexString /re["'\u0060]/ />`, m`<JSON:String /["']/ />`]);
  }
  *SpamexString({
    ctx
  }) {
    yield eat(m`sigilToken: <*Keyword 'm' />`);
    let quot = buildString(ctx.sourceTextFor(yield match(re`/['"\u0060]/`)));
    yield eat(m`openToken: <*Punctuator ${quot} { balanced: ${quot} } />`);
    yield eat(m`content: <Spamex:Matcher />`);
    yield eat(m`closeToken: <*Punctuator ${quot} { balancer: true } />`);
  }
  *CSTMLString({
    ctx
  }) {
    yield eat(m`sigilToken: <*Keyword 't' />`);
    let quot = buildString(ctx.sourceTextFor(yield match(re`/['"\u0060]/`)));
    yield eat(m`openToken: <*Punctuator ${quot} { balanced: ${quot} } />`);
    yield eat(m`content: <CSTML:Tag />`);
    yield eat(m`closeToken: <*Punctuator ${quot} { balancer: true } />`);
  }
  *RegexString({
    ctx
  }) {
    yield eat(m`sigilToken: <*Keyword 're' />`);
    let quot = buildString(ctx.sourceTextFor(yield match(re`/['"\u0060]/`)));
    yield eat(m`openToken: <*Punctuator ${quot} { balanced: ${quot} } />`);
    yield eat(m`content: <Regex:Pattern />`);
    yield eat(m`closeToken: <*Punctuator ${quot} { balancer: true } />`);
  }
  *String() {
    yield eat(m`<IJSON:String />`, null, o({
      suppressNode: true
    }));
  }
  *Identifier() {
    yield eat(re`/[a-zA-Z]+/`);
  }
  *Punctuator() {}
  *Keyword() {}
  *Any() {}
};