/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#a1102d1279bf319c26220b2f19f2921744d78815
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _ArrayDecs, _ObjectDecs, _TupleDecs, _BooleanDecs, _NullDecs, _IntegerDecs, _InfinityDecs, _PunctuatorDecs, _KeywordDecs, _AnyDecs;
import { re, spam as m } from '@bablr/boot';
import { e, eat, eatMatch, match } from '@bablr/helpers/grammar';
import { CoveredBy, Node, InjectFrom } from '@bablr/helpers/decorators';
import * as Space from '@bablr/language-en-blank-space';
import * as productions from '@bablr/helpers/productions';
export const canonicalURL = 'https://bablr.org/languages/core/en/bablr-vm-instruction';
export const dependencies = {
  Space
};
export function* eatMatchTrivia() {
  if (yield match(re`/[ \t\n]/`)) {
    return yield eat(m`#: <*Space:Space />`);
  }
  return null;
}
export const grammar = class BABLRVMInstructionGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Call"], [Node, 2, "SpamexString"], [Node, 2, "CSTMLString"], [Node, 2, "ExpressionString"], [_ArrayDecs, 2, "Array"], [_ObjectDecs, 2, "Object"], [Node, 2, "Property"], [_TupleDecs, 2, "Tuple"], [_BooleanDecs, 2, "Boolean"], [_NullDecs, 2, "Null"], [Node, 2, "Identifier"], [Node, 2, "UnsignedInteger"], [_IntegerDecs, 2, "Integer"], [Node, 2, "Digit"], [_InfinityDecs, 2, "Infinity"], [_PunctuatorDecs, 2, "Punctuator"], [_KeywordDecs, 2, "Keyword"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_ArrayDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _ObjectDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _TupleDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _BooleanDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _NullDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], _IntegerDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), CoveredBy('Number'), Node], _InfinityDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), CoveredBy('Number'), Node], _PunctuatorDecs = [Node, InjectFrom(productions)], _KeywordDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), "Call")]() {
    yield eat(m`callee$: <*Identifier />`);
    yield* eatMatchTrivia();
    yield eat(m`arguments$: <Tuple />`);
  }
  *Expression() {
    yield eat(m`<Any />`, e([m`<Array '[' />`, m`<Object '{' />`, m`<Tuple '(' />`, m`<*Boolean /true|false/ />`, m`<*Null 'null' />`, m`<Number /[\d]|[+-]?Infinity/ />`, m`<SpamexString /m["'\`]/ />`, m`<CSTMLString /c["'\`]/ />`]));
  }
  *JSONExpression() {
    yield eat(m`<Any />`, e([m`<Array '[' />`, m`<Object '{' />`, m`<Tuple '(' />`, m`<*Boolean /true|false/ />`, m`<*Null 'null' />`, m`<Number /[\d]|[+-]?Infinity/ />`]));
  }
  *SpamexString() {
    yield eat(m`sigilToken: <*Keyword 'm' />`);
    let quot = match(re`/['"\`]/`);
    yield eat(m`openToken: <*Punctuator ${quot} balanced=${quot} />`);
    yield eat(m`content: <Spamex:Matcher />`);
    yield eat(m`closeToken: <*Punctuator ${quot} balancer />`);
  }
  *CSTMLString() {
    yield eat(m`sigilToken: <*Keyword 't' />`);
    let quot = match(re`/['"\`]/`);
    yield eat(m`openToken: <*Punctuator ${quot} balanced=${quot} />`);
    yield eat(m`content: <CSTML:Stream />`);
    yield eat(m`closeToken: <*Punctuator ${quot} balancer />`);
  }
  *ExpressionString() {
    yield eat(m`sigilToken: <*Keyword 'e' />`);
    let quot = match(re`/['"\`]/`);
    yield eat(m`openToken: <*Punctuator ${quot} balanced=${quot} />`);
    yield eat(m`content: <Expression />`);
    yield eat(m`closeToken: <*Punctuator ${quot} balancer />`);
  }
  *Array() {
    yield eat(m`openToken: <*Punctuator '[' balanced=']' />`);
    let sp = yield* eatMatchTrivia();
    let first = true;
    while ((first || sp) && (yield match(re`/./`))) {
      yield eat(m`elements[]$: <Expression />`);
      sp = yield* eatMatchTrivia();
      first = false;
    }
    yield eat(m`closeToken: <*Punctuator ']' balancer />`);
  }
  *Object() {
    yield eat(m`openToken: <*Punctuator '{' balanced='}' />`);
    let sp = yield* eatMatchTrivia();
    let first = true;
    while ((first || sp) && (yield match(re`/./`))) {
      yield eat(m`properties[]$: <Property />`);
      sp = yield* eatMatchTrivia();
      first = false;
    }
    yield eat(m`closeToken: <*Punctuator '}' balancer />`);
  }
  *Property() {
    yield eat(m`key$: <*Identifier />`);
    yield* eatMatchTrivia();
    yield eat(m`mapToken: <*Punctuator ':' />`);
    yield* eatMatchTrivia();
    yield eat(m`value$: <Expression />`);
  }
  *Tuple() {
    yield eat(m`openToken: <*Punctuator '(' balanced=')' />`);
    let sp = yield* eatMatchTrivia();
    let first = true;
    while ((first || sp) && (yield match(re`/./`))) {
      yield eat(m`values[]$: <Expression />`);
      sp = yield* eatMatchTrivia();
      first = false;
    }
    yield eat(m`closeToken: <*Punctuator ')' balancer />`);
  }
  *Boolean() {
    yield eat(m`sigilToken: <*Keyword /true|false/ />`);
  }
  *Null() {
    yield eat(m`sigilToken: <*Keyword 'null' />`);
  }
  *Identifier() {
    yield eat(m`/[a-zA-Z]+/`);
  }
  *Number() {
    yield eat(m`<Any />`, e([m`<Integer /-?\d/ />`, m`<Infinity /[+-]I/ />`]));
  }
  *UnsignedInteger() {
    yield eat(m`digits[]: <Digits />`);
  }
  *Integer() {
    yield eatMatch(m`negativeToken: <*Punctuator '-' />`);
    yield eat(m`digits[]$: <Digits />`);
  }
  *Digits() {
    while (yield eatMatch(m`<*Digit /\d/ />`));
  }
  *Digit() {
    yield eat(re`/\d/`);
  }
  *Infinity() {
    yield eatMatch(m`signToken: <*Punctuator /[+-]/ />`);
    yield eat(m`sigilToken: <*Keyword 'Infinity' />`);
  }
  *Punctuator() {}
  *Keyword() {}
  *Any() {}
};